/*
NAVICAT MYSQL DATA TRANSFER

SOURCE SERVER         : 17MYSQL
SOURCE SERVER VERSION : 50556
SOURCE HOST           : 192.168.0.17:3306
SOURCE DATABASE       : MRBIRD

TARGET SERVER TYPE    : MYSQL
TARGET SERVER VERSION : 50556
FILE ENCODING         : 65001

DATE: 2018-11-07 13:40:31
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR T_GOODS 商品套餐表
-- ----------------------------
DROP TABLE IF EXISTS `T_GOODS`;
CREATE TABLE `t_goods` (
  `GOODS_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `GOODS_MONEY` VARCHAR(20) DEFAULT NULL COMMENT '商品价格',
  `GOODS_CYCLE` VARCHAR(50) DEFAULT NULL COMMENT '套餐周期（1天/1个月/3个月/6个月/1年/3年/5年）',

  `REMARK` VARCHAR(50) NOT NULL COMMENT '描述备注',
 
  `CREATE_TIME` VARCHAR(50) DEFAULT NULL COMMENT '创建时间',
 
  PRIMARY KEY (`GOODS_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


-- ----------------------------
-- TABLE STRUCTURE FOR T_ORDER 订单表
-- ----------------------------
DROP TABLE IF EXISTS `t_order`;
CREATE TABLE `T_ORDER` (
  `ORDER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `ORDER_CODE` VARCHAR(50) NOT NULL COMMENT '订单号',
  `USER_ID` BIGINT(20) NOT NULL COMMENT '用户ID',
  `USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
  `PAYMENT` VARCHAR(10) NOT NULL COMMENT '支付方式（1支付宝/2微信）',
  `PAYSTATUS` VARCHAR(10) NOT NULL COMMENT '支付状态（1已支付/2未支付/3支付失败）',
  `GOODS_ID` BIGINT(20) NOT NULL COMMENT '商品ID',

  `RECHARGE_MONEY` VARCHAR(20) DEFAULT NULL COMMENT '充值金额',
  `RECHARGE_CYCLE` VARCHAR(50) DEFAULT NULL COMMENT '充值周期（1天/1个月/3个月/6个月/1年/3年/5年）',
  `CREATE_TIME` VARCHAR(50) DEFAULT NULL COMMENT '创建时间',
  `PAY_TIME` VARCHAR(50) DEFAULT NULL COMMENT '支付时间',
  `EXPIRY_TIME` VARCHAR(50) DEFAULT NULL COMMENT '到期时间',
  PRIMARY KEY (`ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;




INSERT INTO `mrbird`.`t_goods` (
	`GOODS_ID`,
	`GOODS_MONEY`,
	`GOODS_CYCLE`,
	`REMARK`,
	`CREATE_TIME`
)
VALUES
	(
		'4',
		'98',
		'6个月',
		'石狮市',
		'2018-10-13 12:12:35 '
	);




INSERT INTO `mrbird`.`t_order` (
	`ORDER_ID`,
	`ORDER_CODE`,
	`USER_ID`,
	`USERNAME`,
	`PAYMENT`,
	`PAYSTATUS`,
	`GOODS_ID`,
	`RECHARGE_MONEY`,
	`RECHARGE_CYCLE`,
	`CREATE_TIME`,
	`PAY_TIME`,
	`EXPIRY_TIME`
)
VALUES
	(
		'2',
		'2018111070999',
		'1',
		'qiweb',
		'微信支付',
		'支付失败',
		'2',
		'8',
		'一天',
		'2018-10-07 12:12:35',
		'2018-10-08 12:12:35',
		'2018-10-09 12:12:35'
	);


